// Databricks notebook source
// MAGIC %md
// MAGIC 
// MAGIC # [SDS-2.2-360-in-525-03: Geospatial Analytics and Big Data](https://lamastex.github.io/scalable-data-science/360-in-525/2018/03/)
// MAGIC This needs to be edited for Spark 2.2 and for tight integration with other topics like:
// MAGIC 
// MAGIC * geomesa
// MAGIC * twitter geo-located tweets
// MAGIC * etc.
// MAGIC 
// MAGIC Students need to have seen:
// MAGIC 
// MAGIC * scala crash course
// MAGIC * Spark 
// MAGIC   * DataFrames
// MAGIC   * rdds
// MAGIC   * graphX
// MAGIC   * ?

// COMMAND ----------

// MAGIC %md
// MAGIC This is the 2016 version for Middle Earth for a starting point to shape around....
// MAGIC 
// MAGIC The [html source url](https://raw.githubusercontent.com/raazesh-sainudiin/scalable-data-science/master/db/week10/035_ScalableGeoSpatialComputing.html) of this databricks notebook and its recorded Uji ![Image of Uji, Dogen's Time-Being](https://raw.githubusercontent.com/raazesh-sainudiin/scalable-data-science/master/images/UjiTimeBeingDogen.png "uji"):
// MAGIC 
// MAGIC [![sds/uji/week2/week10/035_ScalableGeoSpatialComputing](http://img.youtube.com/vi/0wKxVfeBQBc/0.jpg)](https://www.youtube.com/watch?v=0wKxVfeBQBc?rel=0&autoplay=1&modestbranding=1&start=0&end=753)

// COMMAND ----------

// MAGIC %md
// MAGIC # What is Geospatial Analytics?
// MAGIC 
// MAGIC 
// MAGIC **(watch now 3 minutes and 23 seconds)**:
// MAGIC 
// MAGIC [![Spark Summit East 2016 - What is Geospatial Analytics by Ram Sri Harsha](http://img.youtube.com/vi/1lF1oSjxMT4/0.jpg)](https://www.youtube.com/v/1lF1oSjxMT4?rel=0&autoplay=1&modestbranding=1&start=111&end=314)

// COMMAND ----------

// MAGIC %md
// MAGIC 
// MAGIC # Some Concrete Examples of Scalable Geospatial Analytics
// MAGIC 
// MAGIC ## 1. Let us check out cross-domain data fusion in MSR's Urban Computing Group 
// MAGIC * lots of interesting papers to read at [http://research.microsoft.com/en-us/projects/urbancomputing/](http://research.microsoft.com/en-us/projects/urbancomputing/).
// MAGIC 
// MAGIC Here is an excerpt from the MSR Urban Computing link form above:
// MAGIC 
// MAGIC <p align="justify"><em>Urban computing</em> is a process of acquisition, integration, and analysis of big and heterogeneous data generated by a diversity of sources in urban spaces, such as sensors, devices, vehicles, buildings, and human, to tackle the major issues that cities face, e.g. air pollution, increased energy consumption and traffic congestion. Urban computing connects unobtrusive and ubiquitous sensing technologies, advanced data management and analytics models, and novel visualization methods, to create win-win-win solutions that improve urban <i>environment</i>, <i>human</i> life quality, and <i>city</i> operation systems. Urban computing also helps us understand the nature of urban phenomena and even predict the future of cities. A survey paper on urban computing:</p>
// MAGIC <p align="justify"><b>Yu Zheng, </b>Licia Capra, Ouri Wolfson, Hai Yang. <a href="https://www.microsoft.com/en-us/research/publication/urban-computing-concepts-methodologies-and-applications/">Urban Computing: concepts, methodologies, and applications</a>. ACM Transaction on Intelligent Systems and Technology (<b>ACM TIST</b>). 2014.</p>
// MAGIC <p align="justify"><strong>Urban computing</strong> is also a research project in Microsoft Research, led by Dr. <a href="https://www.microsoft.com/en-us/research/people/yuzheng/"><b>Yu Zheng</b></a> since March 2008. By analyzing the big data generated in urban spaces, a series of urban computing applications have been enabled as follows. One of core research problems is to fuse data across different domains. The other is to learn knowledge from spatio-temporal data, e.g. trajectories.</p>
// MAGIC <p align="justify">Yu Zheng. <a href="https://www.microsoft.com/en-us/research/publication/methodologies-for-cross-domain-data-fusion-an-overview/">Methodologies for Cross-Domain Data Fusion: An Overview</a>. IEEE Transactions on Big Data, vol. 1, no. 1. 2015. (<a href="https://www.microsoft.com/en-us/research/project/cross-domain-data-fusion/">A Tutorial</a>)</p>
// MAGIC <p align="justify">Yu Zheng. <a href="https://www.microsoft.com/en-us/research/publication/trajectory-data-mining-an-overview/">Trajectory Data Mining: An Overview</a>. ACM Transaction on Intelligent Systems and Technology. 2015, vol. 6, issue 3. (<a href="https://www.microsoft.com/en-us/research/project/trajectory-data-mining">A Tutorial</a>)</p>

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Several sciences are naturally geospatial 
// MAGIC * forestry, 
// MAGIC * geography, 
// MAGIC * geology, 
// MAGIC * seismology, 
// MAGIC * etc. etc.
// MAGIC 
// MAGIC See for example the global EQ datastreams from US geological Service below.
// MAGIC 
// MAGIC **A bold idea: **
// MAGIC Imagine the non-parametric inference problem of estimating co-exciting Hawkes-like processes for modelling earth quakes on the entire planet! 
// MAGIC 
// MAGIC For a global data source, see US geological Service's Earthquake hazards Program ["http://earthquake.usgs.gov/data/](http://earthquake.usgs.gov/data/).

// COMMAND ----------

// MAGIC %md
// MAGIC 
// MAGIC Marina, let's add more stuff here...