# Databricks notebook source
# MAGIC %md
# MAGIC ScaDaMaLe Course [site](https://lamastex.github.io/scalable-data-science/sds/3/x/) and [book](https://lamastex.github.io/ScaDaMaLe/index.html)

# COMMAND ----------

# MAGIC %md
# MAGIC This notebook series was updated from the previous one [sds-2-x-dl](https://lamastex.github.io/scalable-data-science/sds/2/x/db/049_DeepLearningIntro/) to work with _Spark 3.0.1_ and _Python3+_. The notebook series was updated on _2021-01-18_. See changes from previous version in table below as well as current flaws that needs revision.  
# MAGIC 
# MAGIC _Thanks to [Christian von Koch](https://www.linkedin.com/in/christianvonkoch/) and [William Anzén](https://www.linkedin.com/in/william-anz%C3%A9n-b52003199/) for their contributions towards making these materials Spark 3.0.1 and Python 3+ compliant._

# COMMAND ----------

# MAGIC %md
# MAGIC ## Table of changes and current flaws
# MAGIC | Notebook | Changes                                                                                                                                                                                       | Current flaws                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
# MAGIC |----------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# MAGIC | 049      |                                                                                                                                                                                               | **cmd6** & **cmd15**: Picture missing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
# MAGIC | 051      | **cmd9**: Changed syntax with dataframes in Pandas. Changed to df.loc for it to work properly. Also changed all .as_matrix() to .values since as_matrix() will be depreciated in future versions  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
# MAGIC | 053      |                                                                                                                                                                                               | **cmd4**: Python WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version. Instructions for updating: Colocations handled automatically by placer. <tf.Variable 'y:0' shape=() dtype=int32_ref>                                                                                                                                                                                                                                                                        |
# MAGIC | 054      |                                                                                                                                                                                               | **cmd15**: Python WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version. Instructions for updating: Colocations handled automatically by placer. <tf.Variable 'y:0' shape=() dtype=int32_ref>                                                                                                                                                                                                                                                                       |
# MAGIC | 055      | **cmd25**: Changed parameter in Dropout layer to rate=1-keep_prob (see comments in code) since keep_prob will be depreciated in future versions.                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
# MAGIC | 057      | **cmd9**: Changed parameter in Dropout layer to rate=1-keep_prob (see comments in code) since keep_prob will be depreciated in future versions.                                                   | **cmd4**: Python WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version. Instructions for updating: Colocations handled automatically by placer. <tf.Variable 'y:0' shape=() dtype=int32_ref>, <br /> WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. Instructions for updating: Use tf.cast instead.  |
# MAGIC | 058      | **cmd7 & cmd9**: Updated path to cifar-10-batches-py                                                                                                                                              | **cmd17**: Python WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version. Instructions for updating: Colocations handled automatically by placer. <tf.Variable 'y:0' shape=() dtype=int32_ref>, <br /> WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. Instructions for updating: Use tf.cast instead. |
# MAGIC | 060      |                                                                                                                                                                                               | **cmd2**: Python WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version. Instructions for updating: Colocations handled automatically by placer. <tf.Variable 'y:0' shape=() dtype=int32_ref>, <br /> WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. Instructions for updating: Use tf.cast instead.  |
# MAGIC | 062      | **cmd21**: Changed parameter in Dropout layer to rate=1-keep_prob (see comments in code) since keep_prob will be depreciated in future versions.                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
# MAGIC | 063      | **cmd16-cmd18**: Does not work to mount on dbfs directly with save_weights() in keras. Workaround: Save first locally on tmp and then move files to dbfs. See https://github.com/h5py/h5py/issues/709   | **cmd16**: Python WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version. Instructions for updating: Colocations handled automatically by placer. <tf.Variable 'y:0' shape=() dtype=int32_ref>, <br /> WARNING:tensorflow:From /databricks/python/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. Instructions for updating: Use tf.cast instead. |

# COMMAND ----------

